### ISSUE TITLE
user asking if she can create a widget for an instagram page on a GCpedia page

### ISSUE THREAD

**Issue by RimaSakr** [tbs-sct/gcpedia#18]

**Comment by Troy-Lawson** [comment]
You can embed an instagram post by copying the embed code from the intagram website and wraping it in <html></html> (see: http://www.gcpedia.gc.ca/wiki/User:Troy.Lawson/sandboxInstagram) but there is no guarantee it will show up properly in every department as security on the browser may prevent it. (see: http://www.gcpedia.gc.ca/wiki/User:Troy.Lawson/sandboxInstagram)
