### ISSUE TITLE
Broken Link to GCpedia home page on Search results page

### ISSUE THREAD

**Issue by MelissaHanna** [tbs-sct/gcpedia#23]
When a user searches for something in the GCpedia search bar the link to return back to GCpedia is broken (This is not on the home page, but on the search results page). 

![broken link](https://cloud.githubusercontent.com/assets/23526340/20927034/923ba1e6-bb8d-11e6-9f85-b880e75e9b7b.png)

**Comment by Troy-Lawson** [comment]
contact Matt Moore

**Comment by pandurx** [comment]
Link seems OK

**Comment by LemieuxGen** [comment]
I just checked it, and it seems ok as well... I'll contact the user to confirm and let you know if we can close the ticket. Thanks!

**Comment by pandurx** [comment]
@LemieuxGen can i close this?

**Comment by MelissaHanna** [comment]
@pandurx  yes! thank you
